import type { Report } from '../interfaces/example-hello-world-rust-wasm-component-lib-hello-world-rust-wasm-component-lib-interface.js';
export { Report };
import type { Circle } from '../interfaces/example-hello-world-rust-wasm-component-lib-hello-world-rust-wasm-component-lib-interface.js';
export { Circle };
import { ExampleHelloWorldRustWasmComponentLibHelloWorldRustWasmComponentLibInterface } from './interfaces/example-hello-world-rust-wasm-component-lib-hello-world-rust-wasm-component-lib-interface.js';
import { WasiCliEnvironment } from './interfaces/wasi-cli-environment.js';
import { WasiCliExit } from './interfaces/wasi-cli-exit.js';
import { WasiCliStderr } from './interfaces/wasi-cli-stderr.js';
import { WasiCliStdin } from './interfaces/wasi-cli-stdin.js';
import { WasiCliStdout } from './interfaces/wasi-cli-stdout.js';
import { WasiClocksWallClock } from './interfaces/wasi-clocks-wall-clock.js';
import { WasiFilesystemPreopens } from './interfaces/wasi-filesystem-preopens.js';
import { WasiFilesystemTypes } from './interfaces/wasi-filesystem-types.js';
import { WasiIoError } from './interfaces/wasi-io-error.js';
import { WasiIoStreams } from './interfaces/wasi-io-streams.js';
export function run(): void;
export function greet(name: string): string;
export function greetMany(names: string[]): string;
export function getReport(): Report;
export function computeArea(circle: Circle): number;
